### ISSUE TITLE
Setup GitHub Pages

### ISSUE THREAD

**Issue by abuango** [abuango/okr-test#5]
## Initiative Description

Review the GitHub documentation and Others to ensure the experience is seamless for the team.

## DRIs

- @abuango 

## Timeline / Milestone

 

FY21Q4

## Action Plans

- [ ] Review GitHub Pages Documentation
- [ ] Review Jekyll Documentation
- [ ] Review Security Options available to restrict Handbook to team
- [ ] https://github.com/abuango/okr-test/issues/9#issue-1051021304
